check_snmp: use MOPL_USE_OPENSSL in _np_state_generate_key
The rename of USE_OPENSSL to MOPL_USE_OPENSSL (#2253) missed this site, so
_np_state_generate_key always compiles the gnulib branch. lib/utils_base.h only
includes sha256.h when MOPL_USE_OPENSSL is undefined, so building check_snmp
against OpenSSL fails:

  check_snmp_helpers.c:918:20: error: variable has incomplete type 'struct sha256_ctx'
  check_snmp_helpers.c:920:22: error: use of undeclared identifier 'this_monitoring_plugin'
  check_snmp_helpers.c:921:3: error: use of undeclared identifier 'sha256_process_bytes'
  check_snmp_helpers.c:924:2: error: use of undeclared identifier 'sha256_finish_ctx'

While here, update the stale name in the matching #endif comment.