plugins/check_ntp_time.c: add missing sockaddr_un -> sockaddr cast
Newer GCC with -Werror=incompatible-pointer-types enabled by default
will choke on this:

  check_ntp_time.c: In function 'offset_request':
  check_ntp_time.c:404:42: error: passing argument 2 of 'connect' from
  incompatible pointer type [-Wincompatible-pointer-types]
  404 | if (connect(socklist[0], &unix_socket, sizeof(unix_socket))) {
      |                          ^~~~~~~~~~~~
      |                          |
      |                          struct sockaddr_un *